### ISSUE TITLE
Use redis password

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp#223] opened 2022-07-11 08:19 UTC
Add info on how to secure redis instance.

Remove port forwarding for redis db.

**Comment by dialexo** [comment] 2022-08-05 15:17
There seems to be a configuration issue on Linux (maybe?). When the devcontainer boots alongside its services defined in `.devcontainer/docker-compose.yml`, it seems that somehow the Redis instance does not pick up the password defined in `.devcontainer/.env`. Which is weird since the official docs say that

> docker compose will automatically pick up a file called .env in the folder containing the docker-compose.yml, but you can also create one in another location.
> https://code.visualstudio.com/remote/advancedcontainers/environment-variables

However the output of `docker logs graasp-redis` on my machine:

```
*** FATAL CONFIG FILE ERROR (Redis 7.0.0) ***
Reading the configuration file, at line 2
>>> 'requirepass'
wrong number of arguments
```

Not sure if it's caused by some weird way VSCode works on Linux, but it seems to work on Docker Desktop for MacOS (my other dev machine works just fine... and I don't see what else is different) :thinking:

**Comment by pyphilia** [comment] 2022-08-10 15:14
Since you're the only one with a linux machine, I reassign this issue to you @dialexo , feel free to tackle it whenever you have free time.

**Closed** 2023-03-14 11:17 UTC
Labels: bug, documentation, chore
